/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackGround: typeof import('./src/components/common/BackGround.vue')['default']
    Characters: typeof import('./src/components/Characters.vue')['default']
    CharactersItem: typeof import('./src/components/components/CharactersItem.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    HeaderBar: typeof import('./src/components/common/HeaderBar.vue')['default']
    Login: typeof import('./src/components/common/Login.vue')['default']
    MarketPlaceHeaderBar: typeof import('./src/components/common/MarketPlaceHeaderBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    Nft: typeof import('./src/components/Nft.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    PageNav: typeof import('./src/components/common/PageNav.vue')['default']
    Partners: typeof import('./src/components/Partners.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Team: typeof import('./src/components/Team.vue')['default']
    TheInput: typeof import('./src/components/common/TheInput.vue')['default']
    TheModal: typeof import('./src/components/common/TheModal.vue')['default']
    Top: typeof import('./src/components/Top.vue')['default']
  }
}
