// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: common.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EUser_UserState int32

const (
	EUser_UserState_Offline EUser_UserState = 0
	EUser_UserState_Online  EUser_UserState = 1
	EUser_UserState_InTeam  EUser_UserState = 2
	EUser_UserState_InGame  EUser_UserState = 3
)

// Enum value maps for EUser_UserState.
var (
	EUser_UserState_name = map[int32]string{
		0: "UserState_Offline",
		1: "UserState_Online",
		2: "UserState_InTeam",
		3: "UserState_InGame",
	}
	EUser_UserState_value = map[string]int32{
		"UserState_Offline": 0,
		"UserState_Online":  1,
		"UserState_InTeam":  2,
		"UserState_InGame":  3,
	}
)

func (x EUser_UserState) Enum() *EUser_UserState {
	p := new(EUser_UserState)
	*p = x
	return p
}

func (x EUser_UserState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EUser_UserState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (EUser_UserState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x EUser_UserState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EUser_UserState.Descriptor instead.
func (EUser_UserState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0, 0}
}

type EItem_ItemType int32

const (
	EItem_ItemType_None    EItem_ItemType = 0
	EItem_ItemType_General EItem_ItemType = 1
	EItem_ItemType_Box     EItem_ItemType = 10
	EItem_ItemType_Coin    EItem_ItemType = 91
	EItem_ItemType_Gem     EItem_ItemType = 92
)

// Enum value maps for EItem_ItemType.
var (
	EItem_ItemType_name = map[int32]string{
		0:  "ItemType_None",
		1:  "ItemType_General",
		10: "ItemType_Box",
		91: "ItemType_Coin",
		92: "ItemType_Gem",
	}
	EItem_ItemType_value = map[string]int32{
		"ItemType_None":    0,
		"ItemType_General": 1,
		"ItemType_Box":     10,
		"ItemType_Coin":    91,
		"ItemType_Gem":     92,
	}
)

func (x EItem_ItemType) Enum() *EItem_ItemType {
	p := new(EItem_ItemType)
	*p = x
	return p
}

func (x EItem_ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EItem_ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (EItem_ItemType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x EItem_ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EItem_ItemType.Descriptor instead.
func (EItem_ItemType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9, 0}
}

type EItem_ItemId int32

const (
	EItem_ItemId_None EItem_ItemId = 0
	EItem_ItemId_Coin EItem_ItemId = 91000001
	EItem_ItemId_Gem  EItem_ItemId = 92000001
)

// Enum value maps for EItem_ItemId.
var (
	EItem_ItemId_name = map[int32]string{
		0:        "ItemId_None",
		91000001: "ItemId_Coin",
		92000001: "ItemId_Gem",
	}
	EItem_ItemId_value = map[string]int32{
		"ItemId_None": 0,
		"ItemId_Coin": 91000001,
		"ItemId_Gem":  92000001,
	}
)

func (x EItem_ItemId) Enum() *EItem_ItemId {
	p := new(EItem_ItemId)
	*p = x
	return p
}

func (x EItem_ItemId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EItem_ItemId) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (EItem_ItemId) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x EItem_ItemId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EItem_ItemId.Descriptor instead.
func (EItem_ItemId) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9, 1}
}

type EItem_DropType int32

const (
	EItem_DropType_None EItem_DropType = 0
	EItem_DropType_1    EItem_DropType = 1
	EItem_DropType_2    EItem_DropType = 2
	EItem_DropType_3    EItem_DropType = 3
)

// Enum value maps for EItem_DropType.
var (
	EItem_DropType_name = map[int32]string{
		0: "DropType_None",
		1: "DropType_1",
		2: "DropType_2",
		3: "DropType_3",
	}
	EItem_DropType_value = map[string]int32{
		"DropType_None": 0,
		"DropType_1":    1,
		"DropType_2":    2,
		"DropType_3":    3,
	}
)

func (x EItem_DropType) Enum() *EItem_DropType {
	p := new(EItem_DropType)
	*p = x
	return p
}

func (x EItem_DropType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EItem_DropType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (EItem_DropType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x EItem_DropType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EItem_DropType.Descriptor instead.
func (EItem_DropType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9, 2}
}

type EItem_TransReason int32

const (
	EItem_TransReason_None EItem_TransReason = 0
	EItem_TransReason_Mail EItem_TransReason = 1
)

// Enum value maps for EItem_TransReason.
var (
	EItem_TransReason_name = map[int32]string{
		0: "TransReason_None",
		1: "TransReason_Mail",
	}
	EItem_TransReason_value = map[string]int32{
		"TransReason_None": 0,
		"TransReason_Mail": 1,
	}
)

func (x EItem_TransReason) Enum() *EItem_TransReason {
	p := new(EItem_TransReason)
	*p = x
	return p
}

func (x EItem_TransReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EItem_TransReason) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (EItem_TransReason) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x EItem_TransReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EItem_TransReason.Descriptor instead.
func (EItem_TransReason) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9, 3}
}

type EMail_MailType int32

const (
	EMail_MailType_None    EMail_MailType = 0
	EMail_MailType_General EMail_MailType = 1
)

// Enum value maps for EMail_MailType.
var (
	EMail_MailType_name = map[int32]string{
		0: "MailType_None",
		1: "MailType_General",
	}
	EMail_MailType_value = map[string]int32{
		"MailType_None":    0,
		"MailType_General": 1,
	}
)

func (x EMail_MailType) Enum() *EMail_MailType {
	p := new(EMail_MailType)
	*p = x
	return p
}

func (x EMail_MailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMail_MailType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (EMail_MailType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x EMail_MailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMail_MailType.Descriptor instead.
func (EMail_MailType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11, 0}
}

type EMail_MailState int32

const (
	EMail_MailState_Init    EMail_MailState = 0
	EMail_MailState_Read    EMail_MailState = 1
	EMail_MailState_Awarded EMail_MailState = 2
)

// Enum value maps for EMail_MailState.
var (
	EMail_MailState_name = map[int32]string{
		0: "MailState_Init",
		1: "MailState_Read",
		2: "MailState_Awarded",
	}
	EMail_MailState_value = map[string]int32{
		"MailState_Init":    0,
		"MailState_Read":    1,
		"MailState_Awarded": 2,
	}
)

func (x EMail_MailState) Enum() *EMail_MailState {
	p := new(EMail_MailState)
	*p = x
	return p
}

func (x EMail_MailState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMail_MailState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[6].Descriptor()
}

func (EMail_MailState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[6]
}

func (x EMail_MailState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMail_MailState.Descriptor instead.
func (EMail_MailState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11, 1}
}

type EMail_MailReadOption int32

const (
	EMail_MailRead_MailIds EMail_MailReadOption = 0
	EMail_MailRead_All     EMail_MailReadOption = 1
)

// Enum value maps for EMail_MailReadOption.
var (
	EMail_MailReadOption_name = map[int32]string{
		0: "MailRead_MailIds",
		1: "MailRead_All",
	}
	EMail_MailReadOption_value = map[string]int32{
		"MailRead_MailIds": 0,
		"MailRead_All":     1,
	}
)

func (x EMail_MailReadOption) Enum() *EMail_MailReadOption {
	p := new(EMail_MailReadOption)
	*p = x
	return p
}

func (x EMail_MailReadOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMail_MailReadOption) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[7].Descriptor()
}

func (EMail_MailReadOption) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[7]
}

func (x EMail_MailReadOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMail_MailReadOption.Descriptor instead.
func (EMail_MailReadOption) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11, 2}
}

type EMail_MailDelOption int32

const (
	EMail_MailDel_MailIds  EMail_MailDelOption = 0
	EMail_MailDel_All      EMail_MailDelOption = 1
	EMail_MailDel_BeenRead EMail_MailDelOption = 2
)

// Enum value maps for EMail_MailDelOption.
var (
	EMail_MailDelOption_name = map[int32]string{
		0: "MailDel_MailIds",
		1: "MailDel_All",
		2: "MailDel_BeenRead",
	}
	EMail_MailDelOption_value = map[string]int32{
		"MailDel_MailIds":  0,
		"MailDel_All":      1,
		"MailDel_BeenRead": 2,
	}
)

func (x EMail_MailDelOption) Enum() *EMail_MailDelOption {
	p := new(EMail_MailDelOption)
	*p = x
	return p
}

func (x EMail_MailDelOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMail_MailDelOption) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[8].Descriptor()
}

func (EMail_MailDelOption) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[8]
}

func (x EMail_MailDelOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMail_MailDelOption.Descriptor instead.
func (EMail_MailDelOption) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11, 3}
}

type EMail_MailGetAwardOption int32

const (
	EMail_MailGetAward_MailId EMail_MailGetAwardOption = 0
	EMail_MailGetAward_All    EMail_MailGetAwardOption = 1
)

// Enum value maps for EMail_MailGetAwardOption.
var (
	EMail_MailGetAwardOption_name = map[int32]string{
		0: "MailGetAward_MailId",
		1: "MailGetAward_All",
	}
	EMail_MailGetAwardOption_value = map[string]int32{
		"MailGetAward_MailId": 0,
		"MailGetAward_All":    1,
	}
)

func (x EMail_MailGetAwardOption) Enum() *EMail_MailGetAwardOption {
	p := new(EMail_MailGetAwardOption)
	*p = x
	return p
}

func (x EMail_MailGetAwardOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMail_MailGetAwardOption) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[9].Descriptor()
}

func (EMail_MailGetAwardOption) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[9]
}

func (x EMail_MailGetAwardOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMail_MailGetAwardOption.Descriptor instead.
func (EMail_MailGetAwardOption) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11, 4}
}

type EMail_EMailType int32

const (
	EMail_EMailType_None     EMail_EMailType = 0
	EMail_EMailType_BindCode EMail_EMailType = 1
)

// Enum value maps for EMail_EMailType.
var (
	EMail_EMailType_name = map[int32]string{
		0: "EMailType_None",
		1: "EMailType_BindCode",
	}
	EMail_EMailType_value = map[string]int32{
		"EMailType_None":     0,
		"EMailType_BindCode": 1,
	}
)

func (x EMail_EMailType) Enum() *EMail_EMailType {
	p := new(EMail_EMailType)
	*p = x
	return p
}

func (x EMail_EMailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMail_EMailType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[10].Descriptor()
}

func (EMail_EMailType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[10]
}

func (x EMail_EMailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMail_EMailType.Descriptor instead.
func (EMail_EMailType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11, 5}
}

type EFriend_ReplyOption int32

const (
	EFriend_Reply_Accept EFriend_ReplyOption = 0
	EFriend_Reply_Reject EFriend_ReplyOption = 1
)

// Enum value maps for EFriend_ReplyOption.
var (
	EFriend_ReplyOption_name = map[int32]string{
		0: "Reply_Accept",
		1: "Reply_Reject",
	}
	EFriend_ReplyOption_value = map[string]int32{
		"Reply_Accept": 0,
		"Reply_Reject": 1,
	}
)

func (x EFriend_ReplyOption) Enum() *EFriend_ReplyOption {
	p := new(EFriend_ReplyOption)
	*p = x
	return p
}

func (x EFriend_ReplyOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EFriend_ReplyOption) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[11].Descriptor()
}

func (EFriend_ReplyOption) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[11]
}

func (x EFriend_ReplyOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EFriend_ReplyOption.Descriptor instead.
func (EFriend_ReplyOption) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13, 0}
}

type EFriend_ListSortType int32

const (
	EFriend_SortType_User_Id     EFriend_ListSortType = 0
	EFriend_SortType_Create_Time EFriend_ListSortType = 1
)

// Enum value maps for EFriend_ListSortType.
var (
	EFriend_ListSortType_name = map[int32]string{
		0: "SortType_User_Id",
		1: "SortType_Create_Time",
	}
	EFriend_ListSortType_value = map[string]int32{
		"SortType_User_Id":     0,
		"SortType_Create_Time": 1,
	}
)

func (x EFriend_ListSortType) Enum() *EFriend_ListSortType {
	p := new(EFriend_ListSortType)
	*p = x
	return p
}

func (x EFriend_ListSortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EFriend_ListSortType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[12].Descriptor()
}

func (EFriend_ListSortType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[12]
}

func (x EFriend_ListSortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EFriend_ListSortType.Descriptor instead.
func (EFriend_ListSortType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13, 1}
}

type ENFT_NFTType int32

const (
	ENFT_NFTType_None   ENFT_NFTType = 0
	ENFT_NFTType_Weapon ENFT_NFTType = 1
)

// Enum value maps for ENFT_NFTType.
var (
	ENFT_NFTType_name = map[int32]string{
		0: "NFTType_None",
		1: "NFTType_Weapon",
	}
	ENFT_NFTType_value = map[string]int32{
		"NFTType_None":   0,
		"NFTType_Weapon": 1,
	}
)

func (x ENFT_NFTType) Enum() *ENFT_NFTType {
	p := new(ENFT_NFTType)
	*p = x
	return p
}

func (x ENFT_NFTType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENFT_NFTType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[13].Descriptor()
}

func (ENFT_NFTType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[13]
}

func (x ENFT_NFTType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENFT_NFTType.Descriptor instead.
func (ENFT_NFTType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15, 0}
}

type EUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EUser) Reset() {
	*x = EUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EUser) ProtoMessage() {}

func (x *EUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EUser.ProtoReflect.Descriptor instead.
func (*EUser) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type Region struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region       string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	TcpGatewayId string `protobuf:"bytes,2,opt,name=tcp_gateway_id,json=tcpGatewayId,proto3" json:"tcp_gateway_id,omitempty"`
}

func (x *Region) Reset() {
	*x = Region{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Region) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Region) GetTcpGatewayId() string {
	if x != nil {
		return x.TcpGatewayId
	}
	return ""
}

type Claims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        uint64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Region        *Region `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Account       string  `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	ClientVersion string  `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Nickname      string  `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	WalletAddr    string  `protobuf:"bytes,6,opt,name=wallet_addr,json=walletAddr,proto3" json:"wallet_addr,omitempty"`
}

func (x *Claims) Reset() {
	*x = Claims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Claims) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Claims) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Claims) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Claims) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Claims) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Claims) GetWalletAddr() string {
	if x != nil {
		return x.WalletAddr
	}
	return ""
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account         string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserId          uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname        string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Icon            string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Email           string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AptosWalletAddr string `protobuf:"bytes,6,opt,name=aptos_wallet_addr,json=aptosWalletAddr,proto3" json:"aptos_wallet_addr,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *AccountInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AccountInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AccountInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AccountInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountInfo) GetAptosWalletAddr() string {
	if x != nil {
		return x.AptosWalletAddr
	}
	return ""
}

type UserProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64          `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account   string          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname  string          `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Icon      uint32          `protobuf:"varint,4,opt,name=icon,proto3" json:"icon,omitempty"`
	IconBox   uint32          `protobuf:"varint,5,opt,name=icon_box,json=iconBox,proto3" json:"icon_box,omitempty"`
	Gender    uint32          `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Vip       uint32          `protobuf:"varint,7,opt,name=vip,proto3" json:"vip,omitempty"`
	UserState EUser_UserState `protobuf:"varint,8,opt,name=user_state,json=userState,proto3,enum=mpb.EUser_UserState" json:"user_state,omitempty"`
	Region    string          `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *UserProfile) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetIcon() uint32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *UserProfile) GetIconBox() uint32 {
	if x != nil {
		return x.IconBox
	}
	return 0
}

func (x *UserProfile) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserProfile) GetVip() uint32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

func (x *UserProfile) GetUserState() EUser_UserState {
	if x != nil {
		return x.UserState
	}
	return EUser_UserState_Offline
}

func (x *UserProfile) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint64       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BasicProfile *UserProfile `protobuf:"bytes,2,opt,name=basic_profile,json=basicProfile,proto3" json:"basic_profile,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetBasicProfile() *UserProfile {
	if x != nil {
		return x.BasicProfile
	}
	return nil
}

type ReqUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ReqUserId) Reset() {
	*x = ReqUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserId) ProtoMessage() {}

func (x *ReqUserId) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserId.ProtoReflect.Descriptor instead.
func (*ReqUserId) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *ReqUserId) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReqUserIdRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Region *Region `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *ReqUserIdRegion) Reset() {
	*x = ReqUserIdRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserIdRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserIdRegion) ProtoMessage() {}

func (x *ReqUserIdRegion) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserIdRegion.ProtoReflect.Descriptor instead.
func (*ReqUserIdRegion) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *ReqUserIdRegion) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqUserIdRegion) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type EItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EItem) Reset() {
	*x = EItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EItem) ProtoMessage() {}

func (x *EItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EItem.ProtoReflect.Descriptor instead.
func (*EItem) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num      uint32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Uuid     uint64 `protobuf:"varint,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BatchId  uint32 `protobuf:"varint,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	ExpireAt int64  `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *Item) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Item) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *Item) GetBatchId() uint32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *Item) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type EMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EMail) Reset() {
	*x = EMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMail) ProtoMessage() {}

func (x *EMail) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMail.ProtoReflect.Descriptor instead.
func (*EMail) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId    uint64            `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"` // generated by mail service
	Receiver  uint64            `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender    uint64            `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"` // 0 means send by system
	SendTime  int64             `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	MailType  EMail_MailType    `protobuf:"varint,5,opt,name=mail_type,json=mailType,proto3,enum=mpb.EMail_MailType" json:"mail_type,omitempty"`
	MailTitle string            `protobuf:"bytes,6,opt,name=mail_title,json=mailTitle,proto3" json:"mail_title,omitempty"`
	MapDatas  map[string]string `protobuf:"bytes,7,rep,name=map_datas,json=mapDatas,proto3" json:"map_datas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Awards    []*Item           `protobuf:"bytes,8,rep,name=awards,proto3" json:"awards,omitempty"`
	State     uint32            `protobuf:"varint,9,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *Mail) GetMailId() uint64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *Mail) GetReceiver() uint64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *Mail) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Mail) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Mail) GetMailType() EMail_MailType {
	if x != nil {
		return x.MailType
	}
	return EMail_MailType_None
}

func (x *Mail) GetMailTitle() string {
	if x != nil {
		return x.MailTitle
	}
	return ""
}

func (x *Mail) GetMapDatas() map[string]string {
	if x != nil {
		return x.MapDatas
	}
	return nil
}

func (x *Mail) GetAwards() []*Item {
	if x != nil {
		return x.Awards
	}
	return nil
}

func (x *Mail) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

// social
type EFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EFriend) Reset() {
	*x = EFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFriend) ProtoMessage() {}

func (x *EFriend) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFriend.ProtoReflect.Descriptor instead.
func (*EFriend) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

// web
type WebAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account         string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserId          uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname        string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Icon            string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Email           string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AptosWalletAddr string `protobuf:"bytes,6,opt,name=aptos_wallet_addr,json=aptosWalletAddr,proto3" json:"aptos_wallet_addr,omitempty"`
}

func (x *WebAccountInfo) Reset() {
	*x = WebAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAccountInfo) ProtoMessage() {}

func (x *WebAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAccountInfo.ProtoReflect.Descriptor instead.
func (*WebAccountInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *WebAccountInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *WebAccountInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebAccountInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *WebAccountInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *WebAccountInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WebAccountInfo) GetAptosWalletAddr() string {
	if x != nil {
		return x.AptosWalletAddr
	}
	return ""
}

// nft
type ENFT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ENFT) Reset() {
	*x = ENFT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ENFT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ENFT) ProtoMessage() {}

func (x *ENFT) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ENFT.ProtoReflect.Descriptor instead.
func (*ENFT) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

type AptosNFTNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftType  uint32 `protobuf:"varint,1,opt,name=nft_type,json=nftType,proto3" json:"nft_type,omitempty"`
	NftId    uint64 `protobuf:"varint,2,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
	Metadata string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *AptosNFTNode) Reset() {
	*x = AptosNFTNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AptosNFTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AptosNFTNode) ProtoMessage() {}

func (x *AptosNFTNode) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AptosNFTNode.ProtoReflect.Descriptor instead.
func (*AptosNFTNode) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *AptosNFTNode) GetNftType() uint32 {
	if x != nil {
		return x.NftType
	}
	return 0
}

func (x *AptosNFTNode) GetNftId() uint64 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *AptosNFTNode) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type AptosNFTMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftId    uint64 `protobuf:"varint,1,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
	MetaData string `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
}

func (x *AptosNFTMetadata) Reset() {
	*x = AptosNFTMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AptosNFTMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AptosNFTMetadata) ProtoMessage() {}

func (x *AptosNFTMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AptosNFTMetadata.ProtoReflect.Descriptor instead.
func (*AptosNFTMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *AptosNFTMetadata) GetNftId() uint64 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *AptosNFTMetadata) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

type AptosNFTNodeV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectionId         string                     `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TokenDataId          string                     `protobuf:"bytes,2,opt,name=token_data_id,json=tokenDataId,proto3" json:"token_data_id,omitempty"`
	Description          string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TokenName            string                     `protobuf:"bytes,4,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenId              uint32                     `protobuf:"varint,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenProperties      *AptosNFTNodeV2_Properties `protobuf:"bytes,6,opt,name=token_properties,json=tokenProperties,proto3" json:"token_properties,omitempty"`
	TokenStandard        string                     `protobuf:"bytes,7,opt,name=token_standard,json=tokenStandard,proto3" json:"token_standard,omitempty"`
	TokenUri             string                     `protobuf:"bytes,8,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
	TransactionTimestamp string                     `protobuf:"bytes,9,opt,name=transaction_timestamp,json=transactionTimestamp,proto3" json:"transaction_timestamp,omitempty"`
}

func (x *AptosNFTNodeV2) Reset() {
	*x = AptosNFTNodeV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AptosNFTNodeV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AptosNFTNodeV2) ProtoMessage() {}

func (x *AptosNFTNodeV2) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AptosNFTNodeV2.ProtoReflect.Descriptor instead.
func (*AptosNFTNodeV2) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *AptosNFTNodeV2) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *AptosNFTNodeV2) GetTokenDataId() string {
	if x != nil {
		return x.TokenDataId
	}
	return ""
}

func (x *AptosNFTNodeV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AptosNFTNodeV2) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *AptosNFTNodeV2) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *AptosNFTNodeV2) GetTokenProperties() *AptosNFTNodeV2_Properties {
	if x != nil {
		return x.TokenProperties
	}
	return nil
}

func (x *AptosNFTNodeV2) GetTokenStandard() string {
	if x != nil {
		return x.TokenStandard
	}
	return ""
}

func (x *AptosNFTNodeV2) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *AptosNFTNodeV2) GetTransactionTimestamp() string {
	if x != nil {
		return x.TransactionTimestamp
	}
	return ""
}

type AptosNFTNodeV2_Properties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prop1      string `protobuf:"bytes,1,opt,name=prop1,proto3" json:"prop1,omitempty"`
	Prop2      string `protobuf:"bytes,2,opt,name=prop2,proto3" json:"prop2,omitempty"`
	Quality    string `protobuf:"bytes,3,opt,name=quality,proto3" json:"quality,omitempty"`
	WeaponId   string `protobuf:"bytes,4,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	WeaponType string `protobuf:"bytes,5,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
}

func (x *AptosNFTNodeV2_Properties) Reset() {
	*x = AptosNFTNodeV2_Properties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AptosNFTNodeV2_Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AptosNFTNodeV2_Properties) ProtoMessage() {}

func (x *AptosNFTNodeV2_Properties) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AptosNFTNodeV2_Properties.ProtoReflect.Descriptor instead.
func (*AptosNFTNodeV2_Properties) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18, 0}
}

func (x *AptosNFTNodeV2_Properties) GetProp1() string {
	if x != nil {
		return x.Prop1
	}
	return ""
}

func (x *AptosNFTNodeV2_Properties) GetProp2() string {
	if x != nil {
		return x.Prop2
	}
	return ""
}

func (x *AptosNFTNodeV2_Properties) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *AptosNFTNodeV2_Properties) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

func (x *AptosNFTNodeV2_Properties) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x6d, 0x70, 0x62, 0x22, 0x6d, 0x0a, 0x05, 0x45, 0x55, 0x73, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x09,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x49, 0x6e, 0x54, 0x65, 0x61, 0x6d, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x10, 0x03, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x46, 0x0a, 0x06, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x0e, 0x74, 0x63, 0x70, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x63, 0x70, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0xb2, 0x01, 0x0a, 0x0b, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x5f, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x61, 0x70, 0x74, 0x6f, 0x73, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x82, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x42, 0x6f, 0x78, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x76, 0x69, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x45, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0d, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0x24, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0xbf, 0x02, 0x0a, 0x05, 0x45, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x6a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a,
	0x0d, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x42, 0x6f, 0x78, 0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x6f, 0x69, 0x6e, 0x10, 0x5b, 0x12, 0x10, 0x0a, 0x0c, 0x49,
	0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65, 0x6d, 0x10, 0x5c, 0x22, 0x40, 0x0a,
	0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x5f, 0x43, 0x6f, 0x69, 0x6e, 0x10, 0xc1, 0x99, 0xb2, 0x2b, 0x12, 0x11, 0x0a, 0x0a,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x5f, 0x47, 0x65, 0x6d, 0x10, 0x81, 0x9e, 0xef, 0x2b, 0x22,
	0x4d, 0x0a, 0x08, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x44,
	0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x32, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x33, 0x10, 0x03, 0x22, 0x39,
	0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x5f, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x22, 0x74, 0x0a, 0x04, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22,
	0x8d, 0x03, 0x0a, 0x05, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x33, 0x0a, 0x08, 0x4d, 0x61, 0x69,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x61, 0x69, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x10, 0x01, 0x22, 0x4a,
	0x0a, 0x09, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4d,
	0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x61,
	0x64, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x61, 0x69, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x5f, 0x41, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x10, 0x02, 0x22, 0x38, 0x0a, 0x0e, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x10,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x5f, 0x41,
	0x6c, 0x6c, 0x10, 0x01, 0x22, 0x4b, 0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c,
	0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x61,
	0x69, 0x6c, 0x44, 0x65, 0x6c, 0x5f, 0x41, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d,
	0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x5f, 0x42, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x10,
	0x02, 0x22, 0x43, 0x0a, 0x12, 0x4d, 0x61, 0x69, 0x6c, 0x47, 0x65, 0x74, 0x41, 0x77, 0x61, 0x72,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x61, 0x69, 0x6c, 0x47,
	0x65, 0x74, 0x41, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x4d, 0x61, 0x69, 0x6c, 0x47, 0x65, 0x74, 0x41, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x41, 0x6c, 0x6c, 0x10, 0x01, 0x22, 0x37, 0x0a, 0x09, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x4d, 0x61, 0x69, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x01, 0x22,
	0xed, 0x02, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x4d, 0x61, 0x69,
	0x6c, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69,
	0x6c, 0x2e, 0x4d, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x6d, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x21, 0x0a, 0x06, 0x61, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x61, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x44, 0x61, 0x74, 0x61, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x7c, 0x0a, 0x07, 0x45, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x22, 0x31, 0x0a, 0x0b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x5f, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x5f, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x10, 0x01, 0x22, 0x3e, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x49,
	0x64, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x54, 0x69, 0x6d, 0x65, 0x10, 0x01, 0x22, 0xb5, 0x01,
	0x0a, 0x0e, 0x57, 0x65, 0x62, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x70, 0x74,
	0x6f, 0x73, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x37, 0x0a, 0x04, 0x45, 0x4e, 0x46, 0x54, 0x22, 0x2f, 0x0a,
	0x07, 0x4e, 0x46, 0x54, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x46, 0x54, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x46,
	0x54, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x10, 0x01, 0x22, 0x5c,
	0x0a, 0x0c, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x66, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6e, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x66, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x10,
	0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x15, 0x0a, 0x06, 0x6e, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x04, 0x0a, 0x0e, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46,
	0x54, 0x4e, 0x6f, 0x64, 0x65, 0x56, 0x32, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x10,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x74,
	0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x56, 0x32, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x72, 0x69, 0x12, 0x33, 0x0a, 0x15, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x1a, 0x90, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x70, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 14)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_common_proto_goTypes = []interface{}{
	(EUser_UserState)(0),              // 0: mpb.EUser.UserState
	(EItem_ItemType)(0),               // 1: mpb.EItem.ItemType
	(EItem_ItemId)(0),                 // 2: mpb.EItem.ItemId
	(EItem_DropType)(0),               // 3: mpb.EItem.DropType
	(EItem_TransReason)(0),            // 4: mpb.EItem.TransReason
	(EMail_MailType)(0),               // 5: mpb.EMail.MailType
	(EMail_MailState)(0),              // 6: mpb.EMail.MailState
	(EMail_MailReadOption)(0),         // 7: mpb.EMail.MailReadOption
	(EMail_MailDelOption)(0),          // 8: mpb.EMail.MailDelOption
	(EMail_MailGetAwardOption)(0),     // 9: mpb.EMail.MailGetAwardOption
	(EMail_EMailType)(0),              // 10: mpb.EMail.EMailType
	(EFriend_ReplyOption)(0),          // 11: mpb.EFriend.ReplyOption
	(EFriend_ListSortType)(0),         // 12: mpb.EFriend.ListSortType
	(ENFT_NFTType)(0),                 // 13: mpb.ENFT.NFTType
	(*EUser)(nil),                     // 14: mpb.EUser
	(*Empty)(nil),                     // 15: mpb.Empty
	(*Region)(nil),                    // 16: mpb.Region
	(*Claims)(nil),                    // 17: mpb.Claims
	(*AccountInfo)(nil),               // 18: mpb.AccountInfo
	(*UserProfile)(nil),               // 19: mpb.UserProfile
	(*UserInfo)(nil),                  // 20: mpb.UserInfo
	(*ReqUserId)(nil),                 // 21: mpb.ReqUserId
	(*ReqUserIdRegion)(nil),           // 22: mpb.ReqUserIdRegion
	(*EItem)(nil),                     // 23: mpb.EItem
	(*Item)(nil),                      // 24: mpb.Item
	(*EMail)(nil),                     // 25: mpb.EMail
	(*Mail)(nil),                      // 26: mpb.Mail
	(*EFriend)(nil),                   // 27: mpb.EFriend
	(*WebAccountInfo)(nil),            // 28: mpb.WebAccountInfo
	(*ENFT)(nil),                      // 29: mpb.ENFT
	(*AptosNFTNode)(nil),              // 30: mpb.AptosNFTNode
	(*AptosNFTMetadata)(nil),          // 31: mpb.AptosNFTMetadata
	(*AptosNFTNodeV2)(nil),            // 32: mpb.AptosNFTNodeV2
	nil,                               // 33: mpb.Mail.MapDatasEntry
	(*AptosNFTNodeV2_Properties)(nil), // 34: mpb.AptosNFTNodeV2.Properties
}
var file_common_proto_depIdxs = []int32{
	16, // 0: mpb.Claims.region:type_name -> mpb.Region
	0,  // 1: mpb.UserProfile.user_state:type_name -> mpb.EUser.UserState
	19, // 2: mpb.UserInfo.basic_profile:type_name -> mpb.UserProfile
	16, // 3: mpb.ReqUserIdRegion.region:type_name -> mpb.Region
	5,  // 4: mpb.Mail.mail_type:type_name -> mpb.EMail.MailType
	33, // 5: mpb.Mail.map_datas:type_name -> mpb.Mail.MapDatasEntry
	24, // 6: mpb.Mail.awards:type_name -> mpb.Item
	34, // 7: mpb.AptosNFTNodeV2.token_properties:type_name -> mpb.AptosNFTNodeV2.Properties
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Region); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserIdRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ENFT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AptosNFTNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AptosNFTMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AptosNFTNodeV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AptosNFTNodeV2_Properties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      14,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
