// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: grpc_apiproxy.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqGetAptosResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AptosAccAddr string `protobuf:"bytes,1,opt,name=aptos_acc_addr,json=aptosAccAddr,proto3" json:"aptos_acc_addr,omitempty"`
}

func (x *ReqGetAptosResources) Reset() {
	*x = ReqGetAptosResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAptosResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAptosResources) ProtoMessage() {}

func (x *ReqGetAptosResources) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAptosResources.ProtoReflect.Descriptor instead.
func (*ReqGetAptosResources) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetAptosResources) GetAptosAccAddr() string {
	if x != nil {
		return x.AptosAccAddr
	}
	return ""
}

type ResGetAptosResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources string `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *ResGetAptosResources) Reset() {
	*x = ResGetAptosResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAptosResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAptosResources) ProtoMessage() {}

func (x *ResGetAptosResources) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAptosResources.ProtoReflect.Descriptor instead.
func (*ResGetAptosResources) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{1}
}

func (x *ResGetAptosResources) GetResources() string {
	if x != nil {
		return x.Resources
	}
	return ""
}

type ReqSendEmailBindCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqSendEmailBindCode) Reset() {
	*x = ReqSendEmailBindCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendEmailBindCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendEmailBindCode) ProtoMessage() {}

func (x *ReqSendEmailBindCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendEmailBindCode.ProtoReflect.Descriptor instead.
func (*ReqSendEmailBindCode) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSendEmailBindCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqSendEmailBindCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ReqSendEmailResetPasswordValidationCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqSendEmailResetPasswordValidationCode) Reset() {
	*x = ReqSendEmailResetPasswordValidationCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendEmailResetPasswordValidationCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendEmailResetPasswordValidationCode) ProtoMessage() {}

func (x *ReqSendEmailResetPasswordValidationCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendEmailResetPasswordValidationCode.ProtoReflect.Descriptor instead.
func (*ReqSendEmailResetPasswordValidationCode) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSendEmailResetPasswordValidationCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqSendEmailResetPasswordValidationCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ReqMoralisGetNFTByWallets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddresses []string `protobuf:"bytes,1,rep,name=wallet_addresses,json=walletAddresses,proto3" json:"wallet_addresses,omitempty"`
	Collections     []string `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
}

func (x *ReqMoralisGetNFTByWallets) Reset() {
	*x = ReqMoralisGetNFTByWallets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMoralisGetNFTByWallets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMoralisGetNFTByWallets) ProtoMessage() {}

func (x *ReqMoralisGetNFTByWallets) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMoralisGetNFTByWallets.ProtoReflect.Descriptor instead.
func (*ReqMoralisGetNFTByWallets) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{4}
}

func (x *ReqMoralisGetNFTByWallets) GetWalletAddresses() []string {
	if x != nil {
		return x.WalletAddresses
	}
	return nil
}

func (x *ReqMoralisGetNFTByWallets) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type ResMoralisGetNFTByWallets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nfts map[string]*ResMoralisGetNFTByWallets_NFTList `protobuf:"bytes,1,rep,name=nfts,proto3" json:"nfts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ResMoralisGetNFTByWallets) Reset() {
	*x = ResMoralisGetNFTByWallets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResMoralisGetNFTByWallets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMoralisGetNFTByWallets) ProtoMessage() {}

func (x *ResMoralisGetNFTByWallets) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMoralisGetNFTByWallets.ProtoReflect.Descriptor instead.
func (*ResMoralisGetNFTByWallets) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{5}
}

func (x *ResMoralisGetNFTByWallets) GetNfts() map[string]*ResMoralisGetNFTByWallets_NFTList {
	if x != nil {
		return x.Nfts
	}
	return nil
}

type ReqGraphiQLGetAccountTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	StartIndex uint64 `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	PageNum    uint64 `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
}

func (x *ReqGraphiQLGetAccountTransactions) Reset() {
	*x = ReqGraphiQLGetAccountTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGraphiQLGetAccountTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGraphiQLGetAccountTransactions) ProtoMessage() {}

func (x *ReqGraphiQLGetAccountTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGraphiQLGetAccountTransactions.ProtoReflect.Descriptor instead.
func (*ReqGraphiQLGetAccountTransactions) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{6}
}

func (x *ReqGraphiQLGetAccountTransactions) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ReqGraphiQLGetAccountTransactions) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *ReqGraphiQLGetAccountTransactions) GetPageNum() uint64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type ResGraphiQLGetAccountTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions *AptosAccountTransactions `protobuf:"bytes,1,opt,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *ResGraphiQLGetAccountTransactions) Reset() {
	*x = ResGraphiQLGetAccountTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGraphiQLGetAccountTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGraphiQLGetAccountTransactions) ProtoMessage() {}

func (x *ResGraphiQLGetAccountTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGraphiQLGetAccountTransactions.ProtoReflect.Descriptor instead.
func (*ResGraphiQLGetAccountTransactions) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{7}
}

func (x *ResGraphiQLGetAccountTransactions) GetTransactions() *AptosAccountTransactions {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ResMoralisGetNFTByWallets_NFTList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*MoralisNFTData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ResMoralisGetNFTByWallets_NFTList) Reset() {
	*x = ResMoralisGetNFTByWallets_NFTList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_apiproxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResMoralisGetNFTByWallets_NFTList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMoralisGetNFTByWallets_NFTList) ProtoMessage() {}

func (x *ResMoralisGetNFTByWallets_NFTList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_apiproxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMoralisGetNFTByWallets_NFTList.ProtoReflect.Descriptor instead.
func (*ResMoralisGetNFTByWallets_NFTList) Descriptor() ([]byte, []int) {
	return file_grpc_apiproxy_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ResMoralisGetNFTByWallets_NFTList) GetList() []*MoralisNFTData {
	if x != nil {
		return x.List
	}
	return nil
}

var File_grpc_apiproxy_proto protoreflect.FileDescriptor

var file_grpc_apiproxy_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41,
	0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x24, 0x0a,
	0x0e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x41, 0x63, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x22, 0x34, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x71,
	0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x53, 0x0a, 0x27, 0x52,
	0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x68, 0x0a, 0x19, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65,
	0x74, 0x4e, 0x46, 0x54, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x29, 0x0a,
	0x10, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xee, 0x01, 0x0a, 0x19, 0x52,
	0x65, 0x73, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65, 0x74, 0x4e, 0x46, 0x54, 0x42,
	0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x04, 0x6e, 0x66, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65, 0x74, 0x4e, 0x46, 0x54, 0x42, 0x79, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x4e, 0x66, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x04, 0x6e, 0x66, 0x74, 0x73, 0x1a, 0x32, 0x0a, 0x07, 0x4e, 0x46, 0x54, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x4e, 0x46, 0x54,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x5f, 0x0a, 0x09, 0x4e, 0x66,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65, 0x74, 0x4e, 0x46, 0x54, 0x42,
	0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x4e, 0x46, 0x54, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x73, 0x0a, 0x21, 0x52,
	0x65, 0x71, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x51, 0x4c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d,
	0x22, 0x66, 0x0a, 0x21, 0x52, 0x65, 0x73, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x51, 0x4c, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x41, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xc3, 0x03, 0x0a, 0x0c, 0x41, 0x50, 0x49,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x52, 0x50, 0x43, 0x12, 0x49, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x19,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x19, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64,
	0x43, 0x6f, 0x64, 0x65, 0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x60, 0x0a, 0x24, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x58, 0x0a, 0x16, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65, 0x74,
	0x4e, 0x46, 0x54, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65, 0x74,
	0x4e, 0x46, 0x54, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x1a, 0x1e, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x73, 0x47, 0x65, 0x74,
	0x4e, 0x46, 0x54, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x70, 0x0a, 0x1e,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x51, 0x4c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x51, 0x4c,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x26, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x51, 0x4c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_apiproxy_proto_rawDescOnce sync.Once
	file_grpc_apiproxy_proto_rawDescData = file_grpc_apiproxy_proto_rawDesc
)

func file_grpc_apiproxy_proto_rawDescGZIP() []byte {
	file_grpc_apiproxy_proto_rawDescOnce.Do(func() {
		file_grpc_apiproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_apiproxy_proto_rawDescData)
	})
	return file_grpc_apiproxy_proto_rawDescData
}

var file_grpc_apiproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grpc_apiproxy_proto_goTypes = []interface{}{
	(*ReqGetAptosResources)(nil),                    // 0: mpb.ReqGetAptosResources
	(*ResGetAptosResources)(nil),                    // 1: mpb.ResGetAptosResources
	(*ReqSendEmailBindCode)(nil),                    // 2: mpb.ReqSendEmailBindCode
	(*ReqSendEmailResetPasswordValidationCode)(nil), // 3: mpb.ReqSendEmailResetPasswordValidationCode
	(*ReqMoralisGetNFTByWallets)(nil),               // 4: mpb.ReqMoralisGetNFTByWallets
	(*ResMoralisGetNFTByWallets)(nil),               // 5: mpb.ResMoralisGetNFTByWallets
	(*ReqGraphiQLGetAccountTransactions)(nil),       // 6: mpb.ReqGraphiQLGetAccountTransactions
	(*ResGraphiQLGetAccountTransactions)(nil),       // 7: mpb.ResGraphiQLGetAccountTransactions
	(*ResMoralisGetNFTByWallets_NFTList)(nil),       // 8: mpb.ResMoralisGetNFTByWallets.NFTList
	nil,                              // 9: mpb.ResMoralisGetNFTByWallets.NftsEntry
	(*AptosAccountTransactions)(nil), // 10: mpb.AptosAccountTransactions
	(*MoralisNFTData)(nil),           // 11: mpb.MoralisNFTData
	(*Empty)(nil),                    // 12: mpb.Empty
}
var file_grpc_apiproxy_proto_depIdxs = []int32{
	9,  // 0: mpb.ResMoralisGetNFTByWallets.nfts:type_name -> mpb.ResMoralisGetNFTByWallets.NftsEntry
	10, // 1: mpb.ResGraphiQLGetAccountTransactions.transactions:type_name -> mpb.AptosAccountTransactions
	11, // 2: mpb.ResMoralisGetNFTByWallets.NFTList.list:type_name -> mpb.MoralisNFTData
	8,  // 3: mpb.ResMoralisGetNFTByWallets.NftsEntry.value:type_name -> mpb.ResMoralisGetNFTByWallets.NFTList
	0,  // 4: mpb.APIProxyGRPC.GetAptosResources:input_type -> mpb.ReqGetAptosResources
	2,  // 5: mpb.APIProxyGRPC.SendEmailBindCode:input_type -> mpb.ReqSendEmailBindCode
	3,  // 6: mpb.APIProxyGRPC.SendEmailResetPasswordValidationCode:input_type -> mpb.ReqSendEmailResetPasswordValidationCode
	4,  // 7: mpb.APIProxyGRPC.MoralisGetNFTByWallets:input_type -> mpb.ReqMoralisGetNFTByWallets
	6,  // 8: mpb.APIProxyGRPC.GraphiQLGetAccountTransactions:input_type -> mpb.ReqGraphiQLGetAccountTransactions
	1,  // 9: mpb.APIProxyGRPC.GetAptosResources:output_type -> mpb.ResGetAptosResources
	12, // 10: mpb.APIProxyGRPC.SendEmailBindCode:output_type -> mpb.Empty
	12, // 11: mpb.APIProxyGRPC.SendEmailResetPasswordValidationCode:output_type -> mpb.Empty
	5,  // 12: mpb.APIProxyGRPC.MoralisGetNFTByWallets:output_type -> mpb.ResMoralisGetNFTByWallets
	7,  // 13: mpb.APIProxyGRPC.GraphiQLGetAccountTransactions:output_type -> mpb.ResGraphiQLGetAccountTransactions
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_apiproxy_proto_init() }
func file_grpc_apiproxy_proto_init() {
	if File_grpc_apiproxy_proto != nil {
		return
	}
	file_common_proto_init()
	file_aptos_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_apiproxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAptosResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAptosResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendEmailBindCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendEmailResetPasswordValidationCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMoralisGetNFTByWallets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResMoralisGetNFTByWallets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGraphiQLGetAccountTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGraphiQLGetAccountTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_apiproxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResMoralisGetNFTByWallets_NFTList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_apiproxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_apiproxy_proto_goTypes,
		DependencyIndexes: file_grpc_apiproxy_proto_depIdxs,
		MessageInfos:      file_grpc_apiproxy_proto_msgTypes,
	}.Build()
	File_grpc_apiproxy_proto = out.File
	file_grpc_apiproxy_proto_rawDesc = nil
	file_grpc_apiproxy_proto_goTypes = nil
	file_grpc_apiproxy_proto_depIdxs = nil
}
