// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: grpc_nft.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqGetAptosNFTs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddr string         `protobuf:"bytes,1,opt,name=wallet_addr,json=walletAddr,proto3" json:"wallet_addr,omitempty"`
	NftTypes   []ENFT_NFTType `protobuf:"varint,2,rep,packed,name=nft_types,json=nftTypes,proto3,enum=mpb.ENFT_NFTType" json:"nft_types,omitempty"`
}

func (x *ReqGetAptosNFTs) Reset() {
	*x = ReqGetAptosNFTs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_nft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAptosNFTs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAptosNFTs) ProtoMessage() {}

func (x *ReqGetAptosNFTs) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_nft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAptosNFTs.ProtoReflect.Descriptor instead.
func (*ReqGetAptosNFTs) Descriptor() ([]byte, []int) {
	return file_grpc_nft_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetAptosNFTs) GetWalletAddr() string {
	if x != nil {
		return x.WalletAddr
	}
	return ""
}

func (x *ReqGetAptosNFTs) GetNftTypes() []ENFT_NFTType {
	if x != nil {
		return x.NftTypes
	}
	return nil
}

type ResGetAptosNFTs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nfts []*AptosNFTNode `protobuf:"bytes,1,rep,name=nfts,proto3" json:"nfts,omitempty"`
}

func (x *ResGetAptosNFTs) Reset() {
	*x = ResGetAptosNFTs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_nft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAptosNFTs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAptosNFTs) ProtoMessage() {}

func (x *ResGetAptosNFTs) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_nft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAptosNFTs.ProtoReflect.Descriptor instead.
func (*ResGetAptosNFTs) Descriptor() ([]byte, []int) {
	return file_grpc_nft_proto_rawDescGZIP(), []int{1}
}

func (x *ResGetAptosNFTs) GetNfts() []*AptosNFTNode {
	if x != nil {
		return x.Nfts
	}
	return nil
}

type ReqGetAptosNFTMetadatas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftIds []uint64 `protobuf:"varint,1,rep,packed,name=nft_ids,json=nftIds,proto3" json:"nft_ids,omitempty"`
}

func (x *ReqGetAptosNFTMetadatas) Reset() {
	*x = ReqGetAptosNFTMetadatas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_nft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAptosNFTMetadatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAptosNFTMetadatas) ProtoMessage() {}

func (x *ReqGetAptosNFTMetadatas) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_nft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAptosNFTMetadatas.ProtoReflect.Descriptor instead.
func (*ReqGetAptosNFTMetadatas) Descriptor() ([]byte, []int) {
	return file_grpc_nft_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGetAptosNFTMetadatas) GetNftIds() []uint64 {
	if x != nil {
		return x.NftIds
	}
	return nil
}

type ResGetAptosNFTMetadatas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadatas []*AptosNFTMetadata `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
}

func (x *ResGetAptosNFTMetadatas) Reset() {
	*x = ResGetAptosNFTMetadatas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_nft_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAptosNFTMetadatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAptosNFTMetadatas) ProtoMessage() {}

func (x *ResGetAptosNFTMetadatas) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_nft_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAptosNFTMetadatas.ProtoReflect.Descriptor instead.
func (*ResGetAptosNFTMetadatas) Descriptor() ([]byte, []int) {
	return file_grpc_nft_proto_rawDescGZIP(), []int{3}
}

func (x *ResGetAptosNFTMetadatas) GetMetadatas() []*AptosNFTMetadata {
	if x != nil {
		return x.Metadatas
	}
	return nil
}

type ReqGetAptosNFTsV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddr string `protobuf:"bytes,2,opt,name=wallet_addr,json=walletAddr,proto3" json:"wallet_addr,omitempty"`
}

func (x *ReqGetAptosNFTsV2) Reset() {
	*x = ReqGetAptosNFTsV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_nft_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAptosNFTsV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAptosNFTsV2) ProtoMessage() {}

func (x *ReqGetAptosNFTsV2) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_nft_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAptosNFTsV2.ProtoReflect.Descriptor instead.
func (*ReqGetAptosNFTsV2) Descriptor() ([]byte, []int) {
	return file_grpc_nft_proto_rawDescGZIP(), []int{4}
}

func (x *ReqGetAptosNFTsV2) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqGetAptosNFTsV2) GetWalletAddr() string {
	if x != nil {
		return x.WalletAddr
	}
	return ""
}

type ResGetAptosNFTsV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nfts []*AptosNFTNodeV2 `protobuf:"bytes,1,rep,name=nfts,proto3" json:"nfts,omitempty"`
}

func (x *ResGetAptosNFTsV2) Reset() {
	*x = ResGetAptosNFTsV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_nft_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAptosNFTsV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAptosNFTsV2) ProtoMessage() {}

func (x *ResGetAptosNFTsV2) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_nft_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAptosNFTsV2.ProtoReflect.Descriptor instead.
func (*ResGetAptosNFTsV2) Descriptor() ([]byte, []int) {
	return file_grpc_nft_proto_rawDescGZIP(), []int{5}
}

func (x *ResGetAptosNFTsV2) GetNfts() []*AptosNFTNodeV2 {
	if x != nil {
		return x.Nfts
	}
	return nil
}

var File_grpc_nft_proto protoreflect.FileDescriptor

var file_grpc_nft_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74,
	0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x2e, 0x0a, 0x09, 0x6e, 0x66, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x70, 0x62,
	0x2e, 0x45, 0x4e, 0x46, 0x54, 0x2e, 0x4e, 0x46, 0x54, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6e,
	0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x6e, 0x66,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41,
	0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x66, 0x74,
	0x73, 0x22, 0x32, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73,
	0x4e, 0x46, 0x54, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x6e,
	0x66, 0x74, 0x49, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41,
	0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x12, 0x33, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e,
	0x46, 0x54, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x22, 0x4d, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41,
	0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x56, 0x32, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x22, 0x3c, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x56, 0x32, 0x12, 0x27, 0x0a, 0x04, 0x6e, 0x66, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x70,
	0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4e, 0x6f, 0x64, 0x65, 0x56, 0x32, 0x52, 0x04, 0x6e, 0x66,
	0x74, 0x73, 0x32, 0xde, 0x01, 0x0a, 0x0a, 0x4e, 0x46, 0x54, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54,
	0x73, 0x12, 0x14, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x1a, 0x14, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x12, 0x52, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x1c, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x1a, 0x1c, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x12, 0x40, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54,
	0x73, 0x56, 0x32, 0x12, 0x16, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54, 0x73, 0x56, 0x32, 0x1a, 0x16, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x4e, 0x46, 0x54,
	0x73, 0x56, 0x32, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_nft_proto_rawDescOnce sync.Once
	file_grpc_nft_proto_rawDescData = file_grpc_nft_proto_rawDesc
)

func file_grpc_nft_proto_rawDescGZIP() []byte {
	file_grpc_nft_proto_rawDescOnce.Do(func() {
		file_grpc_nft_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_nft_proto_rawDescData)
	})
	return file_grpc_nft_proto_rawDescData
}

var file_grpc_nft_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_nft_proto_goTypes = []interface{}{
	(*ReqGetAptosNFTs)(nil),         // 0: mpb.ReqGetAptosNFTs
	(*ResGetAptosNFTs)(nil),         // 1: mpb.ResGetAptosNFTs
	(*ReqGetAptosNFTMetadatas)(nil), // 2: mpb.ReqGetAptosNFTMetadatas
	(*ResGetAptosNFTMetadatas)(nil), // 3: mpb.ResGetAptosNFTMetadatas
	(*ReqGetAptosNFTsV2)(nil),       // 4: mpb.ReqGetAptosNFTsV2
	(*ResGetAptosNFTsV2)(nil),       // 5: mpb.ResGetAptosNFTsV2
	(ENFT_NFTType)(0),               // 6: mpb.ENFT.NFTType
	(*AptosNFTNode)(nil),            // 7: mpb.AptosNFTNode
	(*AptosNFTMetadata)(nil),        // 8: mpb.AptosNFTMetadata
	(*AptosNFTNodeV2)(nil),          // 9: mpb.AptosNFTNodeV2
}
var file_grpc_nft_proto_depIdxs = []int32{
	6, // 0: mpb.ReqGetAptosNFTs.nft_types:type_name -> mpb.ENFT.NFTType
	7, // 1: mpb.ResGetAptosNFTs.nfts:type_name -> mpb.AptosNFTNode
	8, // 2: mpb.ResGetAptosNFTMetadatas.metadatas:type_name -> mpb.AptosNFTMetadata
	9, // 3: mpb.ResGetAptosNFTsV2.nfts:type_name -> mpb.AptosNFTNodeV2
	0, // 4: mpb.NFTService.GetAptosNFTs:input_type -> mpb.ReqGetAptosNFTs
	2, // 5: mpb.NFTService.GetAptosNFTMetadatas:input_type -> mpb.ReqGetAptosNFTMetadatas
	4, // 6: mpb.NFTService.GetAptosNFTsV2:input_type -> mpb.ReqGetAptosNFTsV2
	1, // 7: mpb.NFTService.GetAptosNFTs:output_type -> mpb.ResGetAptosNFTs
	3, // 8: mpb.NFTService.GetAptosNFTMetadatas:output_type -> mpb.ResGetAptosNFTMetadatas
	5, // 9: mpb.NFTService.GetAptosNFTsV2:output_type -> mpb.ResGetAptosNFTsV2
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_nft_proto_init() }
func file_grpc_nft_proto_init() {
	if File_grpc_nft_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_nft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAptosNFTs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_nft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAptosNFTs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_nft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAptosNFTMetadatas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_nft_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAptosNFTMetadatas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_nft_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAptosNFTsV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_nft_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAptosNFTsV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_nft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_nft_proto_goTypes,
		DependencyIndexes: file_grpc_nft_proto_depIdxs,
		MessageInfos:      file_grpc_nft_proto_msgTypes,
	}.Build()
	File_grpc_nft_proto = out.File
	file_grpc_nft_proto_rawDesc = nil
	file_grpc_nft_proto_goTypes = nil
	file_grpc_nft_proto_depIdxs = nil
}
