// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: grpc_account.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqLoginByPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RemoteIp string `protobuf:"bytes,3,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	Region   string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *ReqLoginByPassword) Reset() {
	*x = ReqLoginByPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoginByPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginByPassword) ProtoMessage() {}

func (x *ReqLoginByPassword) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginByPassword.ProtoReflect.Descriptor instead.
func (*ReqLoginByPassword) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLoginByPassword) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqLoginByPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqLoginByPassword) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *ReqLoginByPassword) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ResLoginByPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   *AccountInfo `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Resources string       `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Token     string       `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResLoginByPassword) Reset() {
	*x = ResLoginByPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResLoginByPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLoginByPassword) ProtoMessage() {}

func (x *ResLoginByPassword) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLoginByPassword.ProtoReflect.Descriptor instead.
func (*ResLoginByPassword) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{1}
}

func (x *ResLoginByPassword) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ResLoginByPassword) GetResources() string {
	if x != nil {
		return x.Resources
	}
	return ""
}

func (x *ResLoginByPassword) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReqGetAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *ReqGetAccountInfo) Reset() {
	*x = ReqGetAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAccountInfo) ProtoMessage() {}

func (x *ReqGetAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAccountInfo.ProtoReflect.Descriptor instead.
func (*ReqGetAccountInfo) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGetAccountInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type ReqRegisterAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Device        string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Os            string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	DeviceId      string `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientVersion string `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Region        string `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	RemoteIp      string `protobuf:"bytes,8,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	Platform      string `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *ReqRegisterAccount) Reset() {
	*x = ReqRegisterAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRegisterAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegisterAccount) ProtoMessage() {}

func (x *ReqRegisterAccount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegisterAccount.ProtoReflect.Descriptor instead.
func (*ReqRegisterAccount) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{3}
}

func (x *ReqRegisterAccount) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqRegisterAccount) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqRegisterAccount) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ReqRegisterAccount) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ReqRegisterAccount) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReqRegisterAccount) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ReqRegisterAccount) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ReqRegisterAccount) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *ReqRegisterAccount) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ResGenerateNonce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *ResGenerateNonce) Reset() {
	*x = ResGenerateNonce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGenerateNonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGenerateNonce) ProtoMessage() {}

func (x *ResGenerateNonce) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGenerateNonce.ProtoReflect.Descriptor instead.
func (*ResGenerateNonce) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{4}
}

func (x *ResGenerateNonce) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type ReqWebLoginByWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddr     string `protobuf:"bytes,1,opt,name=wallet_addr,json=walletAddr,proto3" json:"wallet_addr,omitempty"`
	PubKey         []byte `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Nonce          string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	RemoteIp       string `protobuf:"bytes,4,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	Region         string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	AptosFullMsg   string `protobuf:"bytes,6,opt,name=aptos_full_msg,json=aptosFullMsg,proto3" json:"aptos_full_msg,omitempty"`
	AptosSignature string `protobuf:"bytes,7,opt,name=aptos_signature,json=aptosSignature,proto3" json:"aptos_signature,omitempty"`
}

func (x *ReqWebLoginByWallet) Reset() {
	*x = ReqWebLoginByWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqWebLoginByWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqWebLoginByWallet) ProtoMessage() {}

func (x *ReqWebLoginByWallet) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqWebLoginByWallet.ProtoReflect.Descriptor instead.
func (*ReqWebLoginByWallet) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{5}
}

func (x *ReqWebLoginByWallet) GetWalletAddr() string {
	if x != nil {
		return x.WalletAddr
	}
	return ""
}

func (x *ReqWebLoginByWallet) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *ReqWebLoginByWallet) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ReqWebLoginByWallet) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *ReqWebLoginByWallet) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ReqWebLoginByWallet) GetAptosFullMsg() string {
	if x != nil {
		return x.AptosFullMsg
	}
	return ""
}

func (x *ReqWebLoginByWallet) GetAptosSignature() string {
	if x != nil {
		return x.AptosSignature
	}
	return ""
}

type ResWebLoginByWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   *WebAccountInfo `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Resources string          `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Token     string          `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResWebLoginByWallet) Reset() {
	*x = ResWebLoginByWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResWebLoginByWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResWebLoginByWallet) ProtoMessage() {}

func (x *ResWebLoginByWallet) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResWebLoginByWallet.ProtoReflect.Descriptor instead.
func (*ResWebLoginByWallet) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{6}
}

func (x *ResWebLoginByWallet) GetAccount() *WebAccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ResWebLoginByWallet) GetResources() string {
	if x != nil {
		return x.Resources
	}
	return ""
}

func (x *ResWebLoginByWallet) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReqGetAccountInfoByAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *ReqGetAccountInfoByAccount) Reset() {
	*x = ReqGetAccountInfoByAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetAccountInfoByAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetAccountInfoByAccount) ProtoMessage() {}

func (x *ReqGetAccountInfoByAccount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetAccountInfoByAccount.ProtoReflect.Descriptor instead.
func (*ReqGetAccountInfoByAccount) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{7}
}

func (x *ReqGetAccountInfoByAccount) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type ReqGenerateAndSendEmailBindCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ReqGenerateAndSendEmailBindCode) Reset() {
	*x = ReqGenerateAndSendEmailBindCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGenerateAndSendEmailBindCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGenerateAndSendEmailBindCode) ProtoMessage() {}

func (x *ReqGenerateAndSendEmailBindCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGenerateAndSendEmailBindCode.ProtoReflect.Descriptor instead.
func (*ReqGenerateAndSendEmailBindCode) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{8}
}

func (x *ReqGenerateAndSendEmailBindCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ReqWebBindEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code   string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqWebBindEmail) Reset() {
	*x = ReqWebBindEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqWebBindEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqWebBindEmail) ProtoMessage() {}

func (x *ReqWebBindEmail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqWebBindEmail.ProtoReflect.Descriptor instead.
func (*ReqWebBindEmail) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{9}
}

func (x *ReqWebBindEmail) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqWebBindEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqWebBindEmail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResWebBindEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   *WebAccountInfo `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Resources string          `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Token     string          `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ResWebBindEmail) Reset() {
	*x = ResWebBindEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResWebBindEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResWebBindEmail) ProtoMessage() {}

func (x *ResWebBindEmail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResWebBindEmail.ProtoReflect.Descriptor instead.
func (*ResWebBindEmail) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{10}
}

func (x *ResWebBindEmail) GetAccount() *WebAccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ResWebBindEmail) GetResources() string {
	if x != nil {
		return x.Resources
	}
	return ""
}

func (x *ResWebBindEmail) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResGetAptosAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AptosAccAddr string `protobuf:"bytes,1,opt,name=aptos_acc_addr,json=aptosAccAddr,proto3" json:"aptos_acc_addr,omitempty"`
	PubKey       string `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (x *ResGetAptosAccount) Reset() {
	*x = ResGetAptosAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetAptosAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetAptosAccount) ProtoMessage() {}

func (x *ResGetAptosAccount) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetAptosAccount.ProtoReflect.Descriptor instead.
func (*ResGetAptosAccount) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{11}
}

func (x *ResGetAptosAccount) GetAptosAccAddr() string {
	if x != nil {
		return x.AptosAccAddr
	}
	return ""
}

func (x *ResGetAptosAccount) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

type ReqChangePassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
}

func (x *ReqChangePassword) Reset() {
	*x = ReqChangePassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqChangePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangePassword) ProtoMessage() {}

func (x *ReqChangePassword) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangePassword.ProtoReflect.Descriptor instead.
func (*ReqChangePassword) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{12}
}

func (x *ReqChangePassword) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqChangePassword) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ReqChangePassword) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ReqSendEmailResetPasswordCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ReqSendEmailResetPasswordCode) Reset() {
	*x = ReqSendEmailResetPasswordCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSendEmailResetPasswordCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendEmailResetPasswordCode) ProtoMessage() {}

func (x *ReqSendEmailResetPasswordCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendEmailResetPasswordCode.ProtoReflect.Descriptor instead.
func (*ReqSendEmailResetPasswordCode) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{13}
}

func (x *ReqSendEmailResetPasswordCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ReqCheckEmailResetPasswordCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqCheckEmailResetPasswordCode) Reset() {
	*x = ReqCheckEmailResetPasswordCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCheckEmailResetPasswordCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCheckEmailResetPasswordCode) ProtoMessage() {}

func (x *ReqCheckEmailResetPasswordCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCheckEmailResetPasswordCode.ProtoReflect.Descriptor instead.
func (*ReqCheckEmailResetPasswordCode) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{14}
}

func (x *ReqCheckEmailResetPasswordCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqCheckEmailResetPasswordCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ResCheckEmailResetPasswordCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *ResCheckEmailResetPasswordCode) Reset() {
	*x = ResCheckEmailResetPasswordCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResCheckEmailResetPasswordCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResCheckEmailResetPasswordCode) ProtoMessage() {}

func (x *ResCheckEmailResetPasswordCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResCheckEmailResetPasswordCode.ProtoReflect.Descriptor instead.
func (*ResCheckEmailResetPasswordCode) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{15}
}

func (x *ResCheckEmailResetPasswordCode) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type ReqResetPasswordByEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nonce    string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *ReqResetPasswordByEmail) Reset() {
	*x = ReqResetPasswordByEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqResetPasswordByEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResetPasswordByEmail) ProtoMessage() {}

func (x *ReqResetPasswordByEmail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResetPasswordByEmail.ProtoReflect.Descriptor instead.
func (*ReqResetPasswordByEmail) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{16}
}

func (x *ReqResetPasswordByEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqResetPasswordByEmail) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqResetPasswordByEmail) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type ReqResetPasswordByEmailAndVCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReqResetPasswordByEmailAndVCode) Reset() {
	*x = ReqResetPasswordByEmailAndVCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_account_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqResetPasswordByEmailAndVCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResetPasswordByEmailAndVCode) ProtoMessage() {}

func (x *ReqResetPasswordByEmailAndVCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_account_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResetPasswordByEmailAndVCode.ProtoReflect.Descriptor instead.
func (*ReqResetPasswordByEmailAndVCode) Descriptor() ([]byte, []int) {
	return file_grpc_account_proto_rawDescGZIP(), []int{17}
}

func (x *ReqResetPasswordByEmailAndVCode) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqResetPasswordByEmailAndVCode) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqResetPasswordByEmailAndVCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_grpc_account_proto protoreflect.FileDescriptor

var file_grpc_account_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2a,
	0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2d,
	0x0a, 0x11, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x87, 0x02,
	0x0a, 0x12, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x22, 0xe9, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x75,
	0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x49, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x0e, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x46, 0x75, 0x6c,
	0x6c, 0x4d, 0x73, 0x67, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x5f, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61,
	0x70, 0x74, 0x6f, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x78, 0x0a,
	0x13, 0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x57, 0x65, 0x62, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x36, 0x0a, 0x1a, 0x52, 0x65, 0x71, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x37, 0x0a, 0x1f, 0x52, 0x65, 0x71, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x64, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x54, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x57,
	0x65, 0x62, 0x42, 0x69, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x74,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x42, 0x69, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x57, 0x65, 0x62, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x53, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x74, 0x6f, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x70,
	0x74, 0x6f, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x61, 0x70, 0x74, 0x6f, 0x73, 0x41, 0x63, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x72, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x6c, 0x64, 0x5f, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65,
	0x77, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x35, 0x0a,
	0x1d, 0x52, 0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0x4a, 0x0a, 0x1e, 0x52, 0x65, 0x71, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x36, 0x0a, 0x1e, 0x52, 0x65, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x61, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x67, 0x0a, 0x1f, 0x52,
	0x65, 0x71, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42,
	0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x6e, 0x64, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x32, 0x9e, 0x07, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x2e, 0x6d, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x1a, 0x17, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x42, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x32, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x10,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x4c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x10, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32,
	0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x0a, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x1a, 0x18, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x42, 0x79, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x50, 0x0a, 0x1c, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x2e, 0x6d, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x0c,
	0x57, 0x65, 0x62, 0x42, 0x69, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x57, 0x65, 0x62, 0x42, 0x69, 0x6e, 0x64, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x1a, 0x14, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x57, 0x65, 0x62, 0x42,
	0x69, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x3a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x70, 0x74, 0x6f, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x17, 0x2e, 0x6d, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x41, 0x70, 0x74, 0x6f, 0x73, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x0a,
	0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4c, 0x0a, 0x1a, 0x53, 0x65,
	0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x0a, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x67, 0x0a, 0x1b, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x23, 0x2e, 0x6d,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x6e, 0x64, 0x56, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x24, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x41, 0x6e, 0x64, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x62, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_account_proto_rawDescOnce sync.Once
	file_grpc_account_proto_rawDescData = file_grpc_account_proto_rawDesc
)

func file_grpc_account_proto_rawDescGZIP() []byte {
	file_grpc_account_proto_rawDescOnce.Do(func() {
		file_grpc_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_account_proto_rawDescData)
	})
	return file_grpc_account_proto_rawDescData
}

var file_grpc_account_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_grpc_account_proto_goTypes = []interface{}{
	(*ReqLoginByPassword)(nil),              // 0: mpb.ReqLoginByPassword
	(*ResLoginByPassword)(nil),              // 1: mpb.ResLoginByPassword
	(*ReqGetAccountInfo)(nil),               // 2: mpb.ReqGetAccountInfo
	(*ReqRegisterAccount)(nil),              // 3: mpb.ReqRegisterAccount
	(*ResGenerateNonce)(nil),                // 4: mpb.ResGenerateNonce
	(*ReqWebLoginByWallet)(nil),             // 5: mpb.ReqWebLoginByWallet
	(*ResWebLoginByWallet)(nil),             // 6: mpb.ResWebLoginByWallet
	(*ReqGetAccountInfoByAccount)(nil),      // 7: mpb.ReqGetAccountInfoByAccount
	(*ReqGenerateAndSendEmailBindCode)(nil), // 8: mpb.ReqGenerateAndSendEmailBindCode
	(*ReqWebBindEmail)(nil),                 // 9: mpb.ReqWebBindEmail
	(*ResWebBindEmail)(nil),                 // 10: mpb.ResWebBindEmail
	(*ResGetAptosAccount)(nil),              // 11: mpb.ResGetAptosAccount
	(*ReqChangePassword)(nil),               // 12: mpb.ReqChangePassword
	(*ReqSendEmailResetPasswordCode)(nil),   // 13: mpb.ReqSendEmailResetPasswordCode
	(*ReqCheckEmailResetPasswordCode)(nil),  // 14: mpb.ReqCheckEmailResetPasswordCode
	(*ResCheckEmailResetPasswordCode)(nil),  // 15: mpb.ResCheckEmailResetPasswordCode
	(*ReqResetPasswordByEmail)(nil),         // 16: mpb.ReqResetPasswordByEmail
	(*ReqResetPasswordByEmailAndVCode)(nil), // 17: mpb.ReqResetPasswordByEmailAndVCode
	(*AccountInfo)(nil),                     // 18: mpb.AccountInfo
	(*WebAccountInfo)(nil),                  // 19: mpb.WebAccountInfo
	(*ReqUserId)(nil),                       // 20: mpb.ReqUserId
	(*Empty)(nil),                           // 21: mpb.Empty
}
var file_grpc_account_proto_depIdxs = []int32{
	18, // 0: mpb.ResLoginByPassword.account:type_name -> mpb.AccountInfo
	19, // 1: mpb.ResWebLoginByWallet.account:type_name -> mpb.WebAccountInfo
	19, // 2: mpb.ResWebBindEmail.account:type_name -> mpb.WebAccountInfo
	0,  // 3: mpb.AccountService.LoginByPassword:input_type -> mpb.ReqLoginByPassword
	20, // 4: mpb.AccountService.GetAccountInfo:input_type -> mpb.ReqUserId
	7,  // 5: mpb.AccountService.GetAccountInfoByAccount:input_type -> mpb.ReqGetAccountInfoByAccount
	21, // 6: mpb.AccountService.GenerateNonce:input_type -> mpb.Empty
	5,  // 7: mpb.AccountService.WebLoginByWallet:input_type -> mpb.ReqWebLoginByWallet
	8,  // 8: mpb.AccountService.GenerateAndSendEmailBindCode:input_type -> mpb.ReqGenerateAndSendEmailBindCode
	9,  // 9: mpb.AccountService.WebBindEmail:input_type -> mpb.ReqWebBindEmail
	20, // 10: mpb.AccountService.GetAptosAccount:input_type -> mpb.ReqUserId
	12, // 11: mpb.AccountService.ChangePassword:input_type -> mpb.ReqChangePassword
	13, // 12: mpb.AccountService.SendEmailResetPasswordCode:input_type -> mpb.ReqSendEmailResetPasswordCode
	14, // 13: mpb.AccountService.CheckEmailResetPasswordCode:input_type -> mpb.ReqCheckEmailResetPasswordCode
	16, // 14: mpb.AccountService.ResetPasswordByEmail:input_type -> mpb.ReqResetPasswordByEmail
	17, // 15: mpb.AccountService.ResetPasswordByEmailAndVCode:input_type -> mpb.ReqResetPasswordByEmailAndVCode
	1,  // 16: mpb.AccountService.LoginByPassword:output_type -> mpb.ResLoginByPassword
	18, // 17: mpb.AccountService.GetAccountInfo:output_type -> mpb.AccountInfo
	18, // 18: mpb.AccountService.GetAccountInfoByAccount:output_type -> mpb.AccountInfo
	4,  // 19: mpb.AccountService.GenerateNonce:output_type -> mpb.ResGenerateNonce
	6,  // 20: mpb.AccountService.WebLoginByWallet:output_type -> mpb.ResWebLoginByWallet
	21, // 21: mpb.AccountService.GenerateAndSendEmailBindCode:output_type -> mpb.Empty
	10, // 22: mpb.AccountService.WebBindEmail:output_type -> mpb.ResWebBindEmail
	11, // 23: mpb.AccountService.GetAptosAccount:output_type -> mpb.ResGetAptosAccount
	21, // 24: mpb.AccountService.ChangePassword:output_type -> mpb.Empty
	21, // 25: mpb.AccountService.SendEmailResetPasswordCode:output_type -> mpb.Empty
	15, // 26: mpb.AccountService.CheckEmailResetPasswordCode:output_type -> mpb.ResCheckEmailResetPasswordCode
	21, // 27: mpb.AccountService.ResetPasswordByEmail:output_type -> mpb.Empty
	21, // 28: mpb.AccountService.ResetPasswordByEmailAndVCode:output_type -> mpb.Empty
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_account_proto_init() }
func file_grpc_account_proto_init() {
	if File_grpc_account_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLoginByPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResLoginByPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRegisterAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGenerateNonce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqWebLoginByWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResWebLoginByWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetAccountInfoByAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGenerateAndSendEmailBindCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqWebBindEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResWebBindEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetAptosAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqChangePassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSendEmailResetPasswordCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCheckEmailResetPasswordCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResCheckEmailResetPasswordCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqResetPasswordByEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_account_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqResetPasswordByEmailAndVCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_account_proto_goTypes,
		DependencyIndexes: file_grpc_account_proto_depIdxs,
		MessageInfos:      file_grpc_account_proto_msgTypes,
	}.Build()
	File_grpc_account_proto = out.File
	file_grpc_account_proto_rawDesc = nil
	file_grpc_account_proto_goTypes = nil
	file_grpc_account_proto_depIdxs = nil
}
