// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: grpc_apiproxy.proto

package mpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	APIProxyGRPC_GetAptosResources_FullMethodName                    = "/mpb.APIProxyGRPC/GetAptosResources"
	APIProxyGRPC_SendEmailBindCode_FullMethodName                    = "/mpb.APIProxyGRPC/SendEmailBindCode"
	APIProxyGRPC_SendEmailResetPasswordValidationCode_FullMethodName = "/mpb.APIProxyGRPC/SendEmailResetPasswordValidationCode"
	APIProxyGRPC_MoralisGetNFTByWallets_FullMethodName               = "/mpb.APIProxyGRPC/MoralisGetNFTByWallets"
	APIProxyGRPC_GraphiQLGetAccountTransactions_FullMethodName       = "/mpb.APIProxyGRPC/GraphiQLGetAccountTransactions"
)

// APIProxyGRPCClient is the client API for APIProxyGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIProxyGRPCClient interface {
	GetAptosResources(ctx context.Context, in *ReqGetAptosResources, opts ...grpc.CallOption) (*ResGetAptosResources, error)
	SendEmailBindCode(ctx context.Context, in *ReqSendEmailBindCode, opts ...grpc.CallOption) (*Empty, error)
	SendEmailResetPasswordValidationCode(ctx context.Context, in *ReqSendEmailResetPasswordValidationCode, opts ...grpc.CallOption) (*Empty, error)
	MoralisGetNFTByWallets(ctx context.Context, in *ReqMoralisGetNFTByWallets, opts ...grpc.CallOption) (*ResMoralisGetNFTByWallets, error)
	GraphiQLGetAccountTransactions(ctx context.Context, in *ReqGraphiQLGetAccountTransactions, opts ...grpc.CallOption) (*ResGraphiQLGetAccountTransactions, error)
}

type aPIProxyGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIProxyGRPCClient(cc grpc.ClientConnInterface) APIProxyGRPCClient {
	return &aPIProxyGRPCClient{cc}
}

func (c *aPIProxyGRPCClient) GetAptosResources(ctx context.Context, in *ReqGetAptosResources, opts ...grpc.CallOption) (*ResGetAptosResources, error) {
	out := new(ResGetAptosResources)
	err := c.cc.Invoke(ctx, APIProxyGRPC_GetAptosResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) SendEmailBindCode(ctx context.Context, in *ReqSendEmailBindCode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, APIProxyGRPC_SendEmailBindCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) SendEmailResetPasswordValidationCode(ctx context.Context, in *ReqSendEmailResetPasswordValidationCode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, APIProxyGRPC_SendEmailResetPasswordValidationCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) MoralisGetNFTByWallets(ctx context.Context, in *ReqMoralisGetNFTByWallets, opts ...grpc.CallOption) (*ResMoralisGetNFTByWallets, error) {
	out := new(ResMoralisGetNFTByWallets)
	err := c.cc.Invoke(ctx, APIProxyGRPC_MoralisGetNFTByWallets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyGRPCClient) GraphiQLGetAccountTransactions(ctx context.Context, in *ReqGraphiQLGetAccountTransactions, opts ...grpc.CallOption) (*ResGraphiQLGetAccountTransactions, error) {
	out := new(ResGraphiQLGetAccountTransactions)
	err := c.cc.Invoke(ctx, APIProxyGRPC_GraphiQLGetAccountTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIProxyGRPCServer is the server API for APIProxyGRPC service.
// All implementations must embed UnimplementedAPIProxyGRPCServer
// for forward compatibility
type APIProxyGRPCServer interface {
	GetAptosResources(context.Context, *ReqGetAptosResources) (*ResGetAptosResources, error)
	SendEmailBindCode(context.Context, *ReqSendEmailBindCode) (*Empty, error)
	SendEmailResetPasswordValidationCode(context.Context, *ReqSendEmailResetPasswordValidationCode) (*Empty, error)
	MoralisGetNFTByWallets(context.Context, *ReqMoralisGetNFTByWallets) (*ResMoralisGetNFTByWallets, error)
	GraphiQLGetAccountTransactions(context.Context, *ReqGraphiQLGetAccountTransactions) (*ResGraphiQLGetAccountTransactions, error)
	mustEmbedUnimplementedAPIProxyGRPCServer()
}

// UnimplementedAPIProxyGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedAPIProxyGRPCServer struct {
}

func (UnimplementedAPIProxyGRPCServer) GetAptosResources(context.Context, *ReqGetAptosResources) (*ResGetAptosResources, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAptosResources not implemented")
}
func (UnimplementedAPIProxyGRPCServer) SendEmailBindCode(context.Context, *ReqSendEmailBindCode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailBindCode not implemented")
}
func (UnimplementedAPIProxyGRPCServer) SendEmailResetPasswordValidationCode(context.Context, *ReqSendEmailResetPasswordValidationCode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailResetPasswordValidationCode not implemented")
}
func (UnimplementedAPIProxyGRPCServer) MoralisGetNFTByWallets(context.Context, *ReqMoralisGetNFTByWallets) (*ResMoralisGetNFTByWallets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoralisGetNFTByWallets not implemented")
}
func (UnimplementedAPIProxyGRPCServer) GraphiQLGetAccountTransactions(context.Context, *ReqGraphiQLGetAccountTransactions) (*ResGraphiQLGetAccountTransactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GraphiQLGetAccountTransactions not implemented")
}
func (UnimplementedAPIProxyGRPCServer) mustEmbedUnimplementedAPIProxyGRPCServer() {}

// UnsafeAPIProxyGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIProxyGRPCServer will
// result in compilation errors.
type UnsafeAPIProxyGRPCServer interface {
	mustEmbedUnimplementedAPIProxyGRPCServer()
}

func RegisterAPIProxyGRPCServer(s grpc.ServiceRegistrar, srv APIProxyGRPCServer) {
	s.RegisterService(&APIProxyGRPC_ServiceDesc, srv)
}

func _APIProxyGRPC_GetAptosResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetAptosResources)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).GetAptosResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_GetAptosResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).GetAptosResources(ctx, req.(*ReqGetAptosResources))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_SendEmailBindCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSendEmailBindCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).SendEmailBindCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_SendEmailBindCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).SendEmailBindCode(ctx, req.(*ReqSendEmailBindCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_SendEmailResetPasswordValidationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSendEmailResetPasswordValidationCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).SendEmailResetPasswordValidationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_SendEmailResetPasswordValidationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).SendEmailResetPasswordValidationCode(ctx, req.(*ReqSendEmailResetPasswordValidationCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_MoralisGetNFTByWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMoralisGetNFTByWallets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).MoralisGetNFTByWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_MoralisGetNFTByWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).MoralisGetNFTByWallets(ctx, req.(*ReqMoralisGetNFTByWallets))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyGRPC_GraphiQLGetAccountTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGraphiQLGetAccountTransactions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyGRPCServer).GraphiQLGetAccountTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyGRPC_GraphiQLGetAccountTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyGRPCServer).GraphiQLGetAccountTransactions(ctx, req.(*ReqGraphiQLGetAccountTransactions))
	}
	return interceptor(ctx, in, info, handler)
}

// APIProxyGRPC_ServiceDesc is the grpc.ServiceDesc for APIProxyGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIProxyGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpb.APIProxyGRPC",
	HandlerType: (*APIProxyGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAptosResources",
			Handler:    _APIProxyGRPC_GetAptosResources_Handler,
		},
		{
			MethodName: "SendEmailBindCode",
			Handler:    _APIProxyGRPC_SendEmailBindCode_Handler,
		},
		{
			MethodName: "SendEmailResetPasswordValidationCode",
			Handler:    _APIProxyGRPC_SendEmailResetPasswordValidationCode_Handler,
		},
		{
			MethodName: "MoralisGetNFTByWallets",
			Handler:    _APIProxyGRPC_MoralisGetNFTByWallets_Handler,
		},
		{
			MethodName: "GraphiQLGetAccountTransactions",
			Handler:    _APIProxyGRPC_GraphiQLGetAccountTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_apiproxy.proto",
}
