// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.3
// source: resource.proto

package mpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// apiproxy
type EmailAddrRsc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr   string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Host   string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port   string `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *EmailAddrRsc) Reset() {
	*x = EmailAddrRsc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailAddrRsc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddrRsc) ProtoMessage() {}

func (x *EmailAddrRsc) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAddrRsc.ProtoReflect.Descriptor instead.
func (*EmailAddrRsc) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAddrRsc) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *EmailAddrRsc) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *EmailAddrRsc) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EmailAddrRsc) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type MoralisInfoRsc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *MoralisInfoRsc) Reset() {
	*x = MoralisInfoRsc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoralisInfoRsc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoralisInfoRsc) ProtoMessage() {}

func (x *MoralisInfoRsc) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoralisInfoRsc.ProtoReflect.Descriptor instead.
func (*MoralisInfoRsc) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{1}
}

func (x *MoralisInfoRsc) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// nftservice
type NFTCollectionRsc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftType        ENFT_NFTType `protobuf:"varint,1,opt,name=nft_type,json=nftType,proto3,enum=mpb.ENFT_NFTType" json:"nft_type,omitempty"`
	CollectionHash []string     `protobuf:"bytes,2,rep,name=collection_hash,json=collectionHash,proto3" json:"collection_hash,omitempty"`
}

func (x *NFTCollectionRsc) Reset() {
	*x = NFTCollectionRsc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NFTCollectionRsc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFTCollectionRsc) ProtoMessage() {}

func (x *NFTCollectionRsc) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFTCollectionRsc.ProtoReflect.Descriptor instead.
func (*NFTCollectionRsc) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{2}
}

func (x *NFTCollectionRsc) GetNftType() ENFT_NFTType {
	if x != nil {
		return x.NftType
	}
	return ENFT_NFTType_None
}

func (x *NFTCollectionRsc) GetCollectionHash() []string {
	if x != nil {
		return x.CollectionHash
	}
	return nil
}

type NFTConfigRsc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftGraphiqlQueryLimit uint64 `protobuf:"varint,1,opt,name=nft_graphiql_query_limit,json=nftGraphiqlQueryLimit,proto3" json:"nft_graphiql_query_limit,omitempty"`
	NftGraphiqlPageNum    uint64 `protobuf:"varint,2,opt,name=nft_graphiql_page_num,json=nftGraphiqlPageNum,proto3" json:"nft_graphiql_page_num,omitempty"`
	NftTransferEvent      string `protobuf:"bytes,3,opt,name=nft_transfer_event,json=nftTransferEvent,proto3" json:"nft_transfer_event,omitempty"`
	NftBurnEvent          string `protobuf:"bytes,4,opt,name=nft_burn_event,json=nftBurnEvent,proto3" json:"nft_burn_event,omitempty"`
}

func (x *NFTConfigRsc) Reset() {
	*x = NFTConfigRsc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NFTConfigRsc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFTConfigRsc) ProtoMessage() {}

func (x *NFTConfigRsc) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFTConfigRsc.ProtoReflect.Descriptor instead.
func (*NFTConfigRsc) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{3}
}

func (x *NFTConfigRsc) GetNftGraphiqlQueryLimit() uint64 {
	if x != nil {
		return x.NftGraphiqlQueryLimit
	}
	return 0
}

func (x *NFTConfigRsc) GetNftGraphiqlPageNum() uint64 {
	if x != nil {
		return x.NftGraphiqlPageNum
	}
	return 0
}

func (x *NFTConfigRsc) GetNftTransferEvent() string {
	if x != nil {
		return x.NftTransferEvent
	}
	return ""
}

func (x *NFTConfigRsc) GetNftBurnEvent() string {
	if x != nil {
		return x.NftBurnEvent
	}
	return ""
}

var File_resource_proto protoreflect.FileDescriptor

var file_resource_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x29, 0x0a, 0x0e, 0x4d, 0x6f, 0x72, 0x61, 0x6c,
	0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x22, 0x69, 0x0a, 0x10, 0x4e, 0x46, 0x54, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x73, 0x63, 0x12, 0x2c, 0x0a, 0x08, 0x6e, 0x66, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x70, 0x62, 0x2e, 0x45,
	0x4e, 0x46, 0x54, 0x2e, 0x4e, 0x46, 0x54, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6e, 0x66, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0xce, 0x01,
	0x0a, 0x0c, 0x4e, 0x46, 0x54, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x73, 0x63, 0x12, 0x37,
	0x0a, 0x18, 0x6e, 0x66, 0x74, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x71, 0x6c, 0x5f, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x15, 0x6e, 0x66, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x71, 0x6c, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x15, 0x6e, 0x66, 0x74, 0x5f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x69, 0x71, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12, 0x6e, 0x66, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x69, 0x71, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x66,
	0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x66, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x66, 0x74, 0x5f,
	0x62, 0x75, 0x72, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6e, 0x66, 0x74, 0x42, 0x75, 0x72, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_proto_rawDescOnce sync.Once
	file_resource_proto_rawDescData = file_resource_proto_rawDesc
)

func file_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_proto_rawDescData)
	})
	return file_resource_proto_rawDescData
}

var file_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resource_proto_goTypes = []interface{}{
	(*EmailAddrRsc)(nil),     // 0: mpb.EmailAddrRsc
	(*MoralisInfoRsc)(nil),   // 1: mpb.MoralisInfoRsc
	(*NFTCollectionRsc)(nil), // 2: mpb.NFTCollectionRsc
	(*NFTConfigRsc)(nil),     // 3: mpb.NFTConfigRsc
	(ENFT_NFTType)(0),        // 4: mpb.ENFT.NFTType
}
var file_resource_proto_depIdxs = []int32{
	4, // 0: mpb.NFTCollectionRsc.nft_type:type_name -> mpb.ENFT.NFTType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_proto_init() }
func file_resource_proto_init() {
	if File_resource_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailAddrRsc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoralisInfoRsc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NFTCollectionRsc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NFTConfigRsc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_depIdxs,
		MessageInfos:      file_resource_proto_msgTypes,
	}.Build()
	File_resource_proto = out.File
	file_resource_proto_rawDesc = nil
	file_resource_proto_goTypes = nil
	file_resource_proto_depIdxs = nil
}
